/* Simulation code for Boat generated by the OpenModelica Compiler OpenModelica v1.18.1 (64-bit). */
#if !defined(Boat__MODEL_H)
#define Boat__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Boat_functions.h"


extern void Boat_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Boat_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Boat_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Boat_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Boat_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Boat_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Boat_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Boat_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Boat_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Boat_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Boat_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Boat_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Boat_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Boat_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Boat_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Boat_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Boat_relationDescription(int i);
extern void Boat_function_initSample(DATA *data, threadData_t *threadData);
extern int Boat_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Boat_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Boat_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Boat_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Boat_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Boat_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Boat_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Boat_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Boat_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Boat_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Boat_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Boat_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Boat_linear_model_frame(void);
extern const char* Boat_linear_model_datarecovery_frame(void);
extern int Boat_mayer(DATA* data, modelica_real** res, short *);
extern int Boat_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Boat_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Boat_setInputData(DATA *data, const modelica_boolean file);
extern int Boat_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Boat_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Boat_function_updateSynchronous(DATA * data, threadData_t *threadData, long clockIndex);
extern int Boat_function_equationsSynchronous(DATA * data, threadData_t *threadData, long clockIndex);
extern void Boat_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Boat_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Boat_inputNames(DATA* data, char ** names);
extern int Boat_dataReconciliationInputNames(DATA* data, char ** names);
extern int Boat_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Boat_functionLocalKnownVars(DATA*, threadData_t*);
extern int Boat_symbolicInlineSystem(DATA*, threadData_t*);

#include "Boat_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Boat__MODEL_H) */


