/* Additional record code for Boat generated by the OpenModelica Compiler OpenModelica v1.18.1 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Boat_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

